"""initial research schema"""

from alembic import op
import sqlalchemy as sa

revision = "6094166a3f1e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkpoints",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("height", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market_metrics_hourly",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gpu_model", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("definition_version", sa.String(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_metrics_hourly_timestamp"),
        "market_metrics_hourly",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "marketplace_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("chain_id", sa.String(), nullable=False),
        sa.Column("height", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("decoder_version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marketplace_events_height"),
        "marketplace_events",
        ["height"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("chain_id", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("dseq", sa.String(), nullable=False),
        sa.Column("gseq", sa.Integer(), nullable=False),
        sa.Column("oseq", sa.Integer(), nullable=False),
        sa.Column("created_height", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gpu_model", sa.String(), nullable=True),
        sa.Column("gpu_count", sa.Integer(), nullable=True),
        sa.Column("cpu_units", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("memory_bytes", sa.BigInteger(), nullable=True),
        sa.Column("storage_bytes", sa.BigInteger(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_orders_gpu_model"), "orders", ["gpu_model"], unique=False)
    op.create_table(
        "providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("created_height", sa.BigInteger(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_blocks",
        sa.Column("chain_id", sa.String(), nullable=False),
        sa.Column("height", sa.BigInteger(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("block_payload", sa.JSON(), nullable=False),
        sa.Column("results_payload", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decoder_version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("chain_id", "height"),
    )
    op.create_table(
        "raw_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bids",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("created_height", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_denom", sa.String(), nullable=False),
        sa.Column(
            "price_usd_normalized", sa.Numeric(precision=38, scale=18), nullable=True
        ),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bids_order_id"), "bids", ["order_id"], unique=False)
    op.create_index(op.f("ix_bids_provider_id"), "bids", ["provider_id"], unique=False)
    op.create_table(
        "leases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("created_height", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "winning_bid_price", sa.Numeric(precision=38, scale=18), nullable=False
        ),
        sa.Column("price_denom", sa.String(), nullable=False),
        sa.Column(
            "price_usd_normalized", sa.Numeric(precision=38, scale=18), nullable=True
        ),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leases_order_id"), "leases", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_leases_provider_id"), "leases", ["provider_id"], unique=False
    )
    op.create_table(
        "provider_gpu_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gpu_model", sa.String(), nullable=True),
        sa.Column("active", sa.Integer(), nullable=True),
        sa.Column("available", sa.Integer(), nullable=True),
        sa.Column("pending", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column("raw_snapshot_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_snapshot_id"],
            ["raw_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_gpu_snapshots_collected_at"),
        "provider_gpu_snapshots",
        ["collected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_gpu_snapshots_provider_id"),
        "provider_gpu_snapshots",
        ["provider_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_provider_gpu_snapshots_provider_id"),
        table_name="provider_gpu_snapshots",
    )
    op.drop_index(
        op.f("ix_provider_gpu_snapshots_collected_at"),
        table_name="provider_gpu_snapshots",
    )
    op.drop_table("provider_gpu_snapshots")
    op.drop_index(op.f("ix_leases_provider_id"), table_name="leases")
    op.drop_index(op.f("ix_leases_order_id"), table_name="leases")
    op.drop_table("leases")
    op.drop_index(op.f("ix_bids_provider_id"), table_name="bids")
    op.drop_index(op.f("ix_bids_order_id"), table_name="bids")
    op.drop_table("bids")
    op.drop_table("raw_snapshots")
    op.drop_table("raw_blocks")
    op.drop_table("providers")
    op.drop_index(op.f("ix_orders_gpu_model"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_marketplace_events_height"), table_name="marketplace_events")
    op.drop_table("marketplace_events")
    op.drop_index(
        op.f("ix_market_metrics_hourly_timestamp"), table_name="market_metrics_hourly"
    )
    op.drop_table("market_metrics_hourly")
    op.drop_table("job_runs")
    op.drop_table("checkpoints")
    # ### end Alembic commands ###
